services:

  doctorapi:
    image: ${DOCKER_REGISTRY-}doctorapi
    build:
      context: .
      dockerfile: Services/DoctorAPI/DoctorAPI/Dockerfile

  doctor.db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=doctor.db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data