version: '3.8'

services:

  doctorapi:
    image: ${DOCKER_REGISTRY-}doctorapi
    build:
      context: .
      dockerfile: Services/DoctorAPI/DoctorAPI/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"

  doctor.db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=doctor-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
    volumes:
      - doctordata:/var/lib/postgresql/data

  authapi:
    image: ${DOCKER_REGISTRY-}authapi
    build:
      context: .
      dockerfile: Services/AuthAPI/AuthAPI/Dockerfile
    ports:
      - "5100:5100"
      - "5101:5101"

  auth.db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=auth-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    ports:
      - "5433:5432"
    volumes:
      - authdata:/var/lib/postgresql/data

volumes:
    doctordata:
    authdata:

