name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      run_integration_tests:
        description: 'Run integration tests?'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Hospital.sln

      - name: Build
        run: dotnet build Hospital.sln --no-restore --configuration Release

  unit_tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run unit tests
        run: dotnet test ./Tests/DoctorAPI/DoctorAPI.UnitTests/DoctorAPI.UnitTests.csproj --configuration Release --verbosity normal

  integration_tests:
    runs-on: ubuntu-latest
    needs: build
    if: |
      (github.event_name == 'workflow_dispatch' && github.event.inputs.run_integration_tests == 'true') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'run integration tests'))

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run integration tests
        run: dotnet test ./Tests/DoctorAPI/DoctorAPI.IntegrationTests/DoctorAPI.IntegrationTests.csproj --configuration Release --verbosity normal
