name: Run Integration Tests

on:
  workflow_dispatch:

jobs:
  integration_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: HospitalArtifact
          path: HosptialBuild/

      - name: Run integration tests
        run: dotnet test ./Tests/DoctorAPI/DoctorAPI.IntegrationTests/DoctorAPI.IntegrationTests.csproj --configuration Release --verbosity normal